### ISSUE TITLE
Dockerize all the components

### ISSUE THREAD

**Issue by ferrarimarco** [scissor-project/open-scissor#12]
# TODO

- [x] Run https://github.com/hadolint/hadolint during CI builds
- [x] Run https://github.com/RedCoolBeans/dockerlint during CI builds
- [x] List the components to dockerize
- [x] Configure InSpec (see #13)
- [x] Provide a docker-compose.yml to deploy as a service
- [x] Set container hostnames
- [x] Implement InSpec tests for containers
- [x] Implement Dockerfiles for components to dockerize
- [x] Update README (dependencies, how to run tests `./test/test-docker-images.sh --docker-context-path=docker`)
- [x] Add Docker to the list of deps

# Components to Dockerize

- [x] d-streamon-master
- [x] d-streamon-slave
- [x] datasource24
- [x] event-correlator
- [x] flume
- [x] kafka-idmef-converter
- [x] kafka-prelude-connector
- [x] kafka
- [x] zookeeper (it was on the kafka VM)
- [x] logstash
- [x] logstash24
- [x] prelude-manager-oss
- [x] prewikka-oss
- [x] semantics

**Comment by ferrarimarco** [comment]
@StefanoSalsano currently zookeeper and kafka run on the same VM. Should I keep them in the same container?

**Comment by StefanoSalsano** [comment]
if the effort is not big it's good to separate

**Comment by StefanoSalsano** [comment]
but if it introduces issues we may need to address them...

**Comment by ferrarimarco** [comment]
The effort is practically the same. If they run in the same conteiner, we need some kind of process supervisor, like [Spotify is doing](https://github.com/spotify/docker-kafka), otherwise we can have two separate containers, like https://github.com/wurstmeister/kafka-docker.

In the two containers scenario we need at least docker-compose to start the stack (but since we need it anyway it's not a big deal).

**Comment by ferrarimarco** [comment]
UPDATE: zookeeper and kafka have been ported to Docker

cc @StefanoSalsano

**Comment by ferrarimarco** [comment]
@devbrand I have a couple of issues with `flume`.

When I start the docker container I don't see the ports you mentioned available and listening, even if the processes are running.

If you want to try you need Docker (17.09.0-ce), Docker Compose (1.17.1) and InSpec (1.48.0).

Then you can run (after checking out the [`feat/GH-12-dockerization`](https://github.com/scissor-project/open-scissor/tree/feat/GH-12-dockerization) git branch): `./test/test-docker-images.sh --docker-context-path=docker` (this command will build, start and test all the containers).


InSpec tests on the `flume` container will fail.

Relevant InSpec output:

```
    ×  Port 10000 should be listening
     expected `Port 10000.listening?` to return true, got false
     ×  Port 10000 processes should include "java"
     expected [] to include "java"
     ✔  Port 10000 protocols should not include "udp"
     ×  Port 10000 protocols should include "tcp"
     expected [] to include "tcp"
     ×  Port 10000 addresses should include "0.0.0.0"
     expected [] to include "0.0.0.0"
     ×  Port 10000 protocols should include "tcp6"
     expected [] to include "tcp6"
     ×  Port 10000 addresses should include "::"
     expected [] to include "::"
     ×  Port 15222 should be listening
     expected `Port 15222.listening?` to return true, got false
     ×  Port 15222 processes should include "java"
     expected [] to include "java"
     ✔  Port 15222 protocols should not include "udp"
     ×  Port 15222 protocols should include "tcp"
     expected [] to include "tcp"
     ×  Port 15222 addresses should include "0.0.0.0"
     expected [] to include "0.0.0.0"
     ×  Port 15222 protocols should include "tcp6"
     expected [] to include "tcp6"
     ×  Port 15222 addresses should include "::"
     expected [] to include "::"
     ×  Port 20000 should be listening
     expected `Port 20000.listening?` to return true, got false
     ×  Port 20000 processes should include "java"
     expected [] to include "java"
     ✔  Port 20000 protocols should not include "udp"
     ×  Port 20000 protocols should include "tcp"
     expected [] to include "tcp"
     ×  Port 20000 addresses should include "0.0.0.0"
     expected [] to include "0.0.0.0"
     ×  Port 20000 protocols should include "tcp6"
     expected [] to include "tcp6"
     ×  Port 20000 addresses should include "::"
     expected [] to include "::"
     ×  Port 44444 should be listening
     expected `Port 44444.listening?` to return true, got false
     ×  Port 44444 processes should include "java"
     expected [] to include "java"
     ✔  Port 44444 protocols should not include "udp"
     ×  Port 44444 protocols should include "tcp"
     expected [] to include "tcp"
     ×  Port 44444 addresses should include "0.0.0.0"
     expected [] to include "0.0.0.0"
     ×  Port 44444 protocols should include "tcp6"
     expected [] to include "tcp6"
     ×  Port 44444 addresses should include "::"
     expected [] to include "::"
```

**Comment by ferrarimarco** [comment]
Additional points for improvement have been moved to the description of the commit
